# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CelestialBody', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Небесные тела',
                'indexes': [],
                'verbose_name': 'Небесное тело',
                'db_table': 'celestial_bodies',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Citizen', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Жители',
                'indexes': [],
                'verbose_name': 'Житель',
                'db_table': 'citizens',
            },
        ),
        migrations.CreateModel(
            name='EnergyPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EnergyPlant', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Генераторы энегрии',
                'indexes': [],
                'verbose_name': 'Генератор энегрии',
                'db_table': 'energy_generator',
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mine', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Шахты',
                'indexes': [],
                'verbose_name': 'Шахта',
                'db_table': 'mines',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Plant', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Плантации',
                'indexes': [],
                'verbose_name': 'Плантация',
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Race', verbose_name='сцыль на предка')),
            ],
            options={
                'verbose_name_plural': 'Расы',
                'indexes': [],
                'verbose_name': 'Раса',
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='ResourceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Источники ресурсов',
                'indexes': [],
                'verbose_name': 'Источник ресурса',
                'db_table': 'resource_sources',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Типы ресурсов',
                'indexes': [],
                'verbose_name': 'Тип ресурса',
                'db_table': 'resource_types',
            },
        ),
    ]
