# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CelestialBody', verbose_name='сцыль на предка'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Citizen', verbose_name='сцыль на предка'),
        ),
        migrations.AlterField(
            model_name='energyplant',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EnergyPlant', verbose_name='сцыль на предка'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mine', verbose_name='сцыль на предка'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Plant', verbose_name='сцыль на предка'),
        ),
        migrations.AlterField(
            model_name='race',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Race', verbose_name='сцыль на предка'),
        ),
    ]
