# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('hp', models.IntegerField(verbose_name='Хит поинты здания')),
                ('factory_armor', models.IntegerField(verbose_name='Броня сдания')),
            ],
            options={
                'abstract': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ArmorFactory',
            fields=[
                ('basefactory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.BaseFactory')),
            ],
            options={
                'verbose_name_plural': 'Фабрики брони',
                'indexes': [],
                'verbose_name': 'Фабрика брони',
                'db_table': 'armor_factories',
            },
            bases=('production.basefactory',),
        ),
        migrations.CreateModel(
            name='RocketEngineFactory',
            fields=[
                ('basefactory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.BaseFactory')),
            ],
            options={
                'verbose_name_plural': 'Фабрики ракетных двигателей',
                'indexes': [],
                'verbose_name': 'Фабрика ракетных двигателей',
                'db_table': 'rocket_engine_factories',
            },
            bases=('production.basefactory',),
        ),
        migrations.CreateModel(
            name='SpaceShipFactory',
            fields=[
                ('basefactory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.BaseFactory')),
            ],
            options={
                'verbose_name_plural': 'Фабрики космических кораблей',
                'indexes': [],
                'verbose_name': 'Фабрика космических кораблей',
                'db_table': 'space_ship_factories',
            },
            bases=('production.basefactory',),
        ),
        migrations.CreateModel(
            name='WeaponFactory',
            fields=[
                ('basefactory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.BaseFactory')),
            ],
            options={
                'verbose_name_plural': 'Фабрики оружия',
                'indexes': [],
                'verbose_name': 'Фабрика оружия',
                'db_table': 'weapon_factories',
            },
            bases=('production.basefactory',),
        ),
        migrations.AddField(
            model_name='basefactory',
            name='resources',
            field=models.ManyToManyField(to='core.ResourceType', verbose_name='Необходимые ресурсы'),
        ),
    ]
